# Generated by Django 2.1.1 on 2018-11-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name_plural': '角色'},
        ),
    ]
